<?php
/**
 * Password Hash Generator - One-time setup script
 * Run this script to generate a bcrypt hash for the admin password.
 * Usage: php generate_password_hash.php
 *
 * Creates config/auth_config.php with the bcrypt hash.
 * Default password: Admin123!
 */

$password = 'Admin123!';
$hash = password_hash($password, PASSWORD_DEFAULT);

// Create config directory if it doesn't exist
$configDir = __DIR__ . '/config';
if (!is_dir($configDir)) {
    mkdir($configDir, 0755);
}

// Write the hash to config file
$configFile = $configDir . '/auth_config.php';
$content = "<?php\n/**\n * Admin password hash - Generated by generate_password_hash.php\n * Password: Admin123!\n */\nreturn " . var_export($hash, true) . ";\n";
file_put_contents($configFile, $content);

echo "Success! Config created at config/auth_config.php\n";
echo "Password: {$password}\n";
echo "Hash: {$hash}\n";
